CREATE TABLE UserItem
(
    id IDENTITY PRIMARY KEY,
    username VARCHAR(30) UNIQUE NOT NULL,
    password VARCHAR(600) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    name VARCHAR(30) NOT NULL,
    role VARCHAR(10) NOT NULL
);
